let audioCtx = null;
let osc = null;

function startBeep() {
    audioCtx ??= new AudioContext();
    osc = audioCtx.createOscillator();
    osc.type = "square";
    osc.frequency.value = 440;
    osc.connect(audioCtx.destination);
    osc.start();
}

function stopBeep() {
    if (osc) {
        osc.stop();
        osc = null;
    }
}

/** @type {HTMLCanvasElement} */
const canvas = document.getElementById("ch8Display")
const canvasCtx = canvas.getContext("2d");
const imageData = canvasCtx.createImageData(64, 32);
const data = imageData.data;

function drawScreen(pixels) {
    for (let i = 0; i < 2048; i++) {
        const v = pixels[i];          
        data[i*4] = v;
        data[i*4 + 1] = v;
        data[i*4 + 2] = v;
        data[i*4 + 3] = 255;
    }
    canvasCtx.putImageData(imageData, 0, 0)
}


const keyMap = {
    Digit1: 0x1, Digit2: 0x2, Digit3: 0x3, Digit4: 0xC,
    KeyQ:   0x4, KeyW:   0x5, KeyE:   0x6, KeyR:   0xD,
    KeyA:   0x7, KeyS:   0x8, KeyD:   0x9, KeyF:   0xE,
    KeyZ:   0xA, KeyX:   0x0, KeyC:   0xB, KeyV:   0xF,
};

const statusText = document.getElementById("status");
const romSelect = document.getElementById("romSelect");
const romFile = document.getElementById("rom");

// resolves once Go has registered loadRom and setKey
const go = new Go();
const wasmReady = WebAssembly.instantiateStreaming(fetch("main.wasm"), go.importObject).then((result) => {
    go.run(result.instance);
});

async function startRom(buf, name) {
    await wasmReady;
    if (loadRom(new Uint8Array(buf))) {
        statusText.textContent = "Běží: " + name;
    } else {
        statusText.textContent = "ROM je moc velká: " + name;
    }
}

// roms/list.json is generated by build.sh
fetch("roms/list.json")
    .then((res) => res.json())
    .then((names) => {
        for (const name of names) {
            romSelect.add(new Option(name.replace(/\.ch8$/, ""), name));
        }
    })
    .catch(() => {
        statusText.textContent = "Nepodařilo se načíst seznam ROM (spusť ./build.sh).";
    });

romSelect.addEventListener("change", async () => {
    const name = romSelect.value;
    if (!name) {
        return;
    }
    romSelect.blur(); // so game keys don't change the selection
    const res = await fetch("roms/" + encodeURIComponent(name));
    startRom(await res.arrayBuffer(), name);
});

romFile.addEventListener("change", async (e) => {
    const file = e.target.files[0];
    if (!file) {
        return;
    }
    romFile.blur();
    romSelect.value = "";
    startRom(await file.arrayBuffer(), file.name);
});

document.addEventListener("keydown", (e) => {
    if (e.code in keyMap && typeof setKey === "function") {
        setKey(keyMap[e.code], true);
        e.preventDefault();
    }
});

document.addEventListener("keyup", (e) => {
    if (e.code in keyMap && typeof setKey === "function") {
        setKey(keyMap[e.code], false);
        e.preventDefault();
    }
});
